<div class="modal fade" id="criarMotoristaModal" tabindex="-1" role="dialog" aria-labelledby="criarMotoristaModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="criarMotoristaModalLabel">Adicionar Motorista</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/motorista/create" method="post">
                    <div class="form-group">
                        <label for="nome">Nome:</label>
                        <input type="text" required class="form-control" id="nome" name="nome">
                    </div>
                    <div class="form-group">
                        <label for="rg">RG:</label>
                        <input type="text" required maxlength="20" class="form-control" id="rg" name="rg">
                    </div>
                    <div class="form-group">
                        <label for="cpf">CPF:</label>
                        <input type="text" required maxlength="11" class="form-control" id="cpf" name="cpf">
                    </div>
                    <div class="form-group">
                        <label for="telefone">Telefone:</label>
                        <input type="text" class="form-control" id="telefone" name="telefone">
                    </div>
                    <div class="form-group">
                        <label for="veiculo">Veículo:</label>
                        <select class="form-control" id="veiculo" required name="veiculo">
                            <?php

                            foreach ($this->veiculos as $veiculo): ?>
                                <option value="<?= $this->escapeHtml($veiculo['id']) ?>">
                                    <?= $this->escapeHtml($veiculo['modelo']) ?> <?= $this->escapeHtml($veiculo['placa']) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Adicionar Motorista</button>
                </form>
            </div>
        </div>
    </div>
</div>