<?php include 'head.phtml'; // incluindo os js e css necessários

$successMessages = $this->flashMessenger()->getSuccessMessages();
$errorMessages = $this->flashMessenger()->getErrorMessages();
?>

<div class="container">
    <h2 class="mb-3">Lista de Motoristas</h2>

    <?php foreach ($successMessages as $message): ?>
        <div class="alert alert-success">
            <?= $this->escapeHtml($message) ?>
        </div>
    <?php endforeach; ?>

    <?php foreach ($errorMessages as $message): ?>
        <div class="alert alert-danger">
            <?= $this->escapeHtml($message) ?>
        </div>
    <?php endforeach; ?>

    <?php include 'create.phtml'; // incluindo o que existe no modal para criar motorista ?>

    <div class="row">
        <div class="col-md-12">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#criarMotoristaModal">
                Adicionar Motorista
            </button>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-12">
            <table class="table">
                <thead>
                <tr>
                    <th>Nome</th>
                    <th>RG</th>
                    <th>CPF</th>
                    <th>Telefone</th>
                    <th>Veículo</th>
                    <th style="text-align: center;">Ações</th>
                </tr>
                </thead>
                <tbody>

                <?php
                foreach ($this->motoristas as $motorista): ?>
                    <tr>
                        <td><?= $this->escapeHtml($motorista['nome']) ?></td>
                        <td><?= $this->escapeHtml($motorista['rg']) ?></td>
                        <td><?= $this->escapeHtml($motorista['cpf']) ?></td>
                        <td><?= $this->escapeHtml($motorista['telefone']) ?></td>
                        <td><?= $this->escapeHtml($motorista['veiculo']['placa']) ?></td>
                        <td style="text-align: center;">
                            <div style="display: inline-flex; justify-content: center; gap: 10px;">
                                <a href="/motorista/update/<?= $this->escapeHtml($motorista['id']) ?>" class="btn btn-primary">Editar</a>
                                <a href="/motorista/delete/<?= $this->escapeHtml($motorista['id']) ?>" class="btn btn-danger">Excluir</a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="/public/js/script.js"></script>
